DATABASE_NULL = None

PAGE_TYPE_CODE_HTML = "HTML"
PAGE_TYPE_CODE_BINARY = "BINARY"
PAGE_TYPE_CODE_DUPLICATE = "DUPLICATE"
PAGE_TYPE_CODE_FRONTIER = "FRONTIER"

DATA_TYPE_CODE_PDF = "PDF"
DATA_TYPE_CODE_DOC = "DOC"
DATA_TYPE_CODE_DOCX = "DOCX"
DATA_TYPE_CODE_PPT = "PPT"
DATA_TYPE_CODE_PPTX = "PPTX"

IMAGE_CONTENT_TYPE_JPG = "JPG"
IMAGE_CONTENT_TYPE_JPEG = "JPEG"
IMAGE_CONTENT_TYPE_PNG = "PNG"
IMAGE_CONTENT_TYPE_GIF = "GIF"
IMAGE_CONTENT_TYPE_TIFF = "TIFF"
IMAGE_CONTENT_TYPE_TIF = "TIF"
IMAGE_CONTENT_TYPE_RAW = "RAW"
IMAGE_CONTENT_TYPE_UNKNOWN = "UNKNOWN"
