DATABASE_NULL = "NULL"

PAGE_TYPE_CODE_HTML = "HTML"
PAGE_TYPE_CODE_BINARY = "BINARY"
PAGE_TYPE_CODE_DUPLICATE = "DUPLICATE"
PAGE_TYPE_CODE_FRONTIER = "FRONTIER"

DATA_TYPE_CODE_PDF = ".pdf"
DATA_TYPE_CODE_DOC = ".doc"
DATA_TYPE_CODE_DOCX = ".docx"
DATA_TYPE_CODE_PPT = ".ppt"
DATA_TYPE_CODE_PPTX = ".pptx"
