DATABASE_NULL = "NULL"

PAGE_TYPE_CODE_HTML = "HTML"
PAGE_TYPE_CODE_BINARY = "BINARY"
PAGE_TYPE_CODE_DUPLICATE = "DUPLICATE"
PAGE_TYPE_CODE_FRONTIER = "FRONTIER"

DATA_TYPE_CODE_PDF = "PDF"
DATA_TYPE_CODE_DOC = "DOC"
DATA_TYPE_CODE_DOCX = "DOCX"
DATA_TYPE_CODE_PPT = "PPT"
DATA_TYPE_CODE_PPTX = "PPTX"